<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/selects.css">
    <title>Document</title>
</head>
<body>

    <div class="todo">

        <form action="" method="post">
            
        Ambiente:  <select class="input" name="" id="">
                
                <option></option>
                <option>ambiente1</option>
                <option>ambiente2</option>
                <option>ambiente3</option>
            
            </select><br><br><br>

            
        Fecha1:   <input class="input" type="date"><br><br><br>

        
        Fecha2:   <input class="input" type="date"><br><br>

            <input type="submit" class="BotonIngreso" value="Enviar">

        </form>

    </div>

</body>
</html>