<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/cuadros.css">
    <title>Document</title>
</head>
<body>

        
    <table>
            
        <tr>
                
            <th>ID</th>
            <th>Nombre</th>
            <th>Jornada</th>
            <th>Horario</th>
                
        </tr>

        <tr>

            <td>1835768</td>
            <td>ADSI</td>
            <td>Diurna</td>
            <td>13:00 - 18:00</td>

        </tr>

    </table>


</body>
</html>