<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/ests.css">
    <title>Document</title>
</head>
<body>
    
    <div class="contenedor_todo">

    <form action="" method="post">
            
            <h1 class="usuario" id="one">Nº Documento</h1><br>
            <input type="text" class="input"require><br><br><br>

            <h1 class="usuario" id="two">Seleccione ubicacion</h1><br>
            <select class="input" name="" id="">
            
                <option></option>
                <option>lugar</option>
            
            </select><br><br>

            <input type="submit" class="BotonIngreso" value="Registro">
        
        </form>

        <a href="enlaces.php" class="BotonIngreso">Consultas</a>

    </div>

</body>
</html>