<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/cuadros.css">
    <title>Document</title>
</head>
<body>
       
    <table>
        
        <tr>
            
            <th>ID</th>
            <th>Nombre</th>
            <th>Detalle lugar</th>
            
        </tr>

        <tr>

            <td>1</td>
            <td>Ambiente 1</td>
            <td>piso 1 bloque 2</td>

        </tr>

    </table>
    

</body>
</html>