<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/cuadros.css">
    <title>Document</title>
</head>
<body>

        
    <table>
        
        <tr>
            
            <th>ID</th>
            <th>Nombre</th>
            <th>Rol</th>
            <th>Ficha</th>
            
        </tr>

        <tr>

            <td>123456789</td>
            <td>Pepito Perez</td>
            <td>Aprendiz</td>
            <td>18357682</td>

        </tr>

    </table>

    </div>
</body>
</html>